Completed prep-javascript-variables.
stefancarrera/prep-0221-code-solutions pull request #10
Opened 2021-02-24 04:22 UTC by stefancarrera

![java1](https://user-images.githubusercontent.com/53131688/108947144-7e506e80-7625-11eb-936b-bd30db503e90.png)

2021-02-24 04:22 UTC, thebearingedge requested changes
Great! Just one small change.

2021-02-24 04:22 UTC, thebearingedge commented on prep-javascript-variables/index.html
> +    var never =
For this variable, you can leave out the `=` entirely.

```js
var never;
```

2021-02-24 05:05 UTC, stefancarrera commented
![java1-5](https://user-images.githubusercontent.com/53131688/108950314-a216b300-762b-11eb-8fc3-2ad73ffd6fe9.png)

2021-02-25 22:49 UTC, thebearingedge approved these changes
Nice! 👍

2021-02-25 23:04 UTC, merged